name: Update license year

on:
  schedule:
    - cron: 0 3 1 1 *

permissions: read-all

jobs:
  update-license-year:
    runs-on: ubuntu-slim
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: FantasticFiasco/action-update-license-year@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: |
            src/**/*.pyi
            LICENSE
          commitTitle: ðŸ“„ Update license year
          prTitle: Happy New Year
